### ISSUE TITLE
Unable to restore <CACHE FOLDER>. Cache does not exist

### ISSUE THREAD

**Issue by andreas-venturini** [drone-plugins/drone-cache#3]
I am currently experimenting with drone and a rails project. Drone seems not to be able to properly cache bundled gems. For each build it throws an error stating that it cannot find any cache. 

```
[info] Pulling image plugins/drone-cache:latest
Restoring cache /tmp/bundler
Unable to restore /tmp/bundler. Cache does not exist
Restoring cache from master branch
Unable to restore /tmp/bundler from master branch.
```

in my .drone.yml

``` yaml
build:
  image: ruby:2.1
  commands:
    - ...
    - bundle install --path=/tmp/bundler -j 4 --without development production
    - ...

cache:
  mount:
    - /tmp/bundler
```

I am running the latest drone:0.4 docker container.
